<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

define('CLI_SCRIPT', true);
define('CLI_VMOODLE_OVERRIDE', true);

require(dirname(dirname(dirname(dirname(__FILE__)))).'/config.php'); // Global moodle config file.
require_once($CFG->dirroot.'/lib/clilib.php'); // CLI only functions.
require_once($CFG->dirroot.'/mod/sharedresource/locallib.php');

// Ensure options are blanck.
unset($options);

// Now get cli options.

list($options, $unrecognized) = cli_get_params(
    array(
        'help'             => false,
        'debug'            => false,
        'classifids'       => false
    ),
    array(
        'h' => 'help',
        'd' => 'debug',
        'C' => 'classifids'
    )
);

if ($unrecognized) {
    $unrecognized = implode("\n  ", $unrecognized);
    cli_error("$unrecognized is not a recognized attribute\n");
}

if ($options['help']) {
    $help = "
Synchronizes one or several sharedresource taxonomies (local model). Taxons must reside in
the mdl_sharedresource_taxonomy table. (All other location unsupported). Classif names
will be matched by shortname, even if addressed by id. Token in a classification
will not be remapped to new ids and will be matched by idnumber. Undefined id numbers
will be added and assigned a autogenerated idnumber.

WARNING : this script only works when all databases share the same connexion and the
master host can write into all databases.

Options:
    -h, --help              Print out this help
    -d, --debug             Turn on debug mode
    -c, --classifids        A list of numeric classification ids. If not provided, will sync all classifications.
    -C, --classifnames      A coma separated (quoted) list of classification shortnames. If not provided, will sync all classifications.

Examples :
    php mod/sharedresource/cli/sync_taxonomy.php --classifnames=\"Classif 1\",\"Classif 2\"

"; // TODO: localize - to be translated later when everything is finished.

    echo $help;
    die;
}

if (!empty($options['debug'])) {
    $CFG->debug = E_ALL;
}

// Start updating.
// Linux only implementation.

if (!empty($options['classifids'])) {
    $idlist = explode(',', $options['classifids']);
    foreach ($idlist as $iix => $id) {
        $idlist[$iix] = trim($id);
    }

    list($insql, $inparams) = $DB->get_in_or_equal($idlist);

    $select = "
        table = 'sharedresource_taxonomy' AND
        id $insql
    ";

    $classifs = $DB->get_records_select('sharedresource_classif', $select, $inparams);
} else if (!empty($options['classifnames'])) {
    $namelist = explode(',', $options['classifnames']);
    foreach ($namelist as $iix => $name) {
        $name = str_replace('"', '', trim($name)); // Unquote.
        $namelist[$iix] = $name;
    }

    list($insql, $inparams) = $DB->get_in_or_equal($idlist);

    $select = "
        table = 'sharedresource_taxonomy' AND
        shortname $insql
    ";

    $classifs = $DB->get_records_select('sharedresource_classif', $select, $inparams);
} else {
    $classifs = $DB->get_records('sharedresource_classif', array('table' => 'sharedresource_taxonomy'));
}

if (empty($classifs)) {
    die "No taxonomies to process. ";
}

foreach ($classifs as $classif) {
    sharedresource_sync_classification($classif);
}

echo "Done.\n";